apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    App: "{{.Values.name}}"
  name: "{{.Values.name}}"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      App: "{{.Values.name}}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        App: "{{.Values.name}}"
    spec:
      automountServiceAccountToken: true
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: "{{.Values.name}}"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always